version: '3.4'

services:

  branding.api:
    image: eshop/branding.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Branding/Branding.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  appointment.api:
    image: eshop/appointment.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Appointment/Appointment.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  servicecatalog.api:
    image: eshop/servicecatalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/ServiceCatalog.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  business.api:
    image: eshop/business.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Business/Business.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  webmvcbackend:
    image: eshop/webmvcbackend:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVCBackend/Dockerfile    
    depends_on:
      - business.api
      - servicecatalog.api
      - identity.api
      - appointment.api

  mobilereservationagg:
    image: eshop/mobilereservationagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Mobile.Bff.Reservation/aggregator/Dockerfile

  mobilereservationapigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile


  basket.api:
    image: eshop/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile    
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq

  catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  identity.api:
    image: eshop/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data

  ordering.api:
    image: eshop/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  ordering.backgroundtasks:
    image: eshop/ordering.backgroundtasks:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.BackgroundTasks/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  marketing.api:
    image: eshop/marketing.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webmvc:
    image: eshop/webmvc:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile    
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webstatus:
    image: eshop/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

  payment.api:
    image: eshop/payment.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq    
    
  locations.api:
    image: eshop/locations.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Location/Locations.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: mysql/mysql-server:${TAG:-latest}
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
      MYSQL_HOST: localhost
    restart: always
    volumes:
      - ~/mysql/data:/var/lib/mysql
      - ~/mysql/conf.d:/etc/mysql/conf.d
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
      - ~/mysql/conf.d/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"    # Important: In a production environment your should remove the external port

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3-management-alpine

  mobileshoppingapigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
 
  mobilemarketingapigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
 
  webshoppingapigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile

  webmarketingapigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile

  mobileshoppingagg:
    image: eshop/mobileshoppingagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile

  webshoppingagg:
    image: eshop/webshoppingagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile

  ordering.signalrhub:
    image: eshop/ordering.signalrhub:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.SignalrHub/Dockerfile

