export default [
    {
        Id: '4',
        IsAvailability: true,
        StartDateTime: new Date('2018-10-13 08:30'),
        EndDateTime: new Date('2018-10-30 22:30'),
        StaffId: 'xxxxxx',
        ServiceItemId: 'xxxx',
        LocationId: 'xxxx',
        SiteId: 'vj4ueTKK',
        BookableEndDateTime: 'vj4ueTKK',
        Sunday: true,
        Monday: true,
        Tuesday: true,
        Wednesday: false,
        Thursday: true,
        Friday: true,
        Saturday: true,
    },
]