global using Basket.API.IntegrationEvents.Events;
global using Basket.API.Model;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Eva.eShop.BuildingBlocks.EventBus.Abstractions;
global using Eva.eShop.Services.Basket.API.Controllers;
global using Eva.eShop.Services.Basket.API.Model;
global using Microsoft.Extensions.Logging;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.Security.Claims;
global using System.Threading.Tasks;
global using Xunit;
global using IBasketIdentityService = Eva.eShop.Services.Basket.API.Services.IIdentityService;
global using Eva.eShop.WebMVC.Controllers;
global using Eva.eShop.WebMVC.Services;
global using Eva.eShop.WebMVC.ViewModels;
global using BasketModel = Eva.eShop.WebMVC.ViewModels.Basket;
