// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Sequence.Migrations
{
    [DbContext(typeof(SeqContext))]
    partial class SeqContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Demo.API.Sequence.KeyAlloc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IncrementSize");

                    b.Property<long>("MaxValue");

                    b.Property<long>("MinValue");

                    b.Property<long>("NextValue");

                    b.Property<string>("SequenceName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("SequenceName");

                    b.ToTable("tbKeyAlloc");
                });
#pragma warning restore 612, 618
        }
    }
}
