export default interface RegisterUserCommand {
    TenantId: string,
    InvitationIdentifier: string,
    Username: string,
    Password: string,
    FirstName: string,
    LastName: string,
    Enabled: boolean,
    StartDate: Date,
    EndDate: Date,
    EmailAddress: string,
    PrimaryTelephone: string,
    SecondaryTelephone: string,
    AddressStreetAddress: string,
    AddressCity: string,
    AddressStateProvince: string,
    AddressPostalCode: string,
    AddressCountryCode: string,
  }